package JavaTechnoStudy.day37.tasks.task2;

import org.junit.Test;

public class myTest {

    @Test

    public void test1() throws Exception {

//        CarPurchase toyota = new CarPurchase();
//        String expected =
//        toyota.buy(Condition.WASTE);

        // try and catch lerde (exception) test yapabilir miyiz? Sor.


    }


}
